// AI model configuration.
//
// The predator chatbot is fixed to the VT Custom (StagePilot) session-based API,
// which also predicts the grooming stage automatically. Educational feedback is
// generated by a single OpenAI model via the Responses API (see app/api/feedback).

// VT Custom (StagePilot) base URL — predator chatbot.
export const VT_CUSTOM_BASE_URL = 'https://rylai.cs.vt.edu/llm';

// Feedback model — used with the OpenAI Responses API (direct OpenAI, OPENAI_API_KEY).
// Override via the FEEDBACK_MODEL env var. Verify availability for your API key;
// fall back to a current model (e.g. 'gpt-4o') if the preferred model is unavailable.
export const FEEDBACK_MODEL = process.env.FEEDBACK_MODEL || 'gpt-5.5';
