DROP INDEX `users_username_idx`;--> statement-breakpoint
ALTER TABLE `users` ADD `educator_id` text REFERENCES users(id) ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE `users` ADD `open_enrollment` integer DEFAULT true NOT NULL;--> statement-breakpoint
UPDATE users SET educator_id = (SELECT ac.educator_id FROM access_codes ac WHERE ac.used_by_user_id = users.id ORDER BY ac.used_at ASC LIMIT 1) WHERE user_type = 'user' AND educator_id IS NULL AND EXISTS (SELECT 1 FROM access_codes ac WHERE ac.used_by_user_id = users.id);--> statement-breakpoint
UPDATE users SET educator_id = (SELECT s.user_id FROM scenario_progress sp JOIN scenarios s ON s.id = sp.scenario_id WHERE sp.user_id = users.id ORDER BY sp.last_visited_at DESC LIMIT 1) WHERE user_type = 'user' AND educator_id IS NULL AND EXISTS (SELECT 1 FROM scenario_progress sp WHERE sp.user_id = users.id);--> statement-breakpoint
UPDATE users SET educator_id = (SELECT s.user_id FROM user_messages um JOIN scenarios s ON s.id = um.scenario_id WHERE um.user_id = users.id ORDER BY um.created_at DESC LIMIT 1) WHERE user_type = 'user' AND educator_id IS NULL AND EXISTS (SELECT 1 FROM user_messages um WHERE um.user_id = users.id);--> statement-breakpoint
UPDATE users SET educator_id = (SELECT u2.id FROM users u2 WHERE u2.user_type = 'admin' AND u2.educator_id IS NULL AND u2.created_at <= users.created_at ORDER BY u2.created_at DESC LIMIT 1) WHERE user_type = 'user' AND educator_id IS NULL AND EXISTS (SELECT 1 FROM users u2 WHERE u2.user_type = 'admin' AND u2.educator_id IS NULL AND u2.created_at <= users.created_at);--> statement-breakpoint
UPDATE users SET educator_id = (SELECT u2.id FROM users u2 WHERE u2.user_type = 'admin' AND u2.educator_id IS NULL ORDER BY u2.created_at ASC LIMIT 1) WHERE user_type = 'user' AND educator_id IS NULL AND EXISTS (SELECT 1 FROM users u2 WHERE u2.user_type = 'admin' AND u2.educator_id IS NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `users_educator_username_idx` ON `users` (`educator_id`,`username`) WHERE "users"."educator_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX `users_username_idx` ON `users` (`username`) WHERE "users"."educator_id" IS NULL;
